// Generated HOMEii Music Flow localization dictionary.
// Keep keys stable. Translate only the string values.
const messages = Object.freeze({
  "ui.a_guided_music_wizard": "Un asistente de música guiado",
  "ui.a_radio_station": "Una estación de radio",
  "ui.accent_color": "Color de acento",
  "ui.actions": "acciones",
  "ui.actions_2": "Acciones",
  "ui.active_days": "Días activos",
  "ui.active_player_helper": "Asistente de reproductor activo",
  "ui.active_player_helper_must_be_an_input_text_entity": "El asistente de reproductor activo debe ser una entidad input_text",
  "ui.active_players": "Reproductores activos",
  "ui.add": "Agregar",
  "ui.add_to_queue": "Agregar a la cola",
  "ui.add_to_selection": "Agregar a la selección",
  "ui.added_to_liked": "Agregado a favoritos",
  "ui.added_to_music_assistant_liked": "Agregado a favoritos de Music Assistant",
  "ui.added_to_queue": "Agregado a la cola",
  "ui.added_to_studio_queue": "Agregado a la cola del estudio",
  "ui.adds_motion_to_the_background_layers_subtle_keeps_it_calm_strong_is_noti": "Agrega movimiento a las capas de fondo. Sutil lo mantiene calmado, Fuerte es notorio y Extremo es el aspecto animado más audaz.",
  "ui.adds_to_the_current_volume_only_during_announcements_then_restores_the_p": "Aumenta el volumen actual solo durante los anuncios, luego restaura el volumen anterior.",
  "ui.after_run": "Después de ejecutar",
  "ui.album": "Álbum",
  "ui.albums": "Álbumes",
  "ui.all_albums": "Todos los álbumes",
  "ui.all_artists": "Todos los artistas",
  "ui.all_countries": "Todos los países",
  "ui.all_player_groups_disconnected": "Todos los grupos de reproductores desconectados",
  "ui.all_players": "Todos los reproductores",
  "ui.all_players_2": "todos los reproductores",
  "ui.all_podcasts": "Todos los podcasts",
  "ui.all_tracks": "Todas las canciones",
  "ui.allow_local_likes": "Permitir favoritos locales",
  "ui.always_visible": "Siempre visible",
  "ui.announce": "Anunciar",
  "ui.announce_to_all_players": "Anunciar a todos los reproductores",
  "ui.announcement": "Anuncio",
  "ui.announcement_failed_with_error": "Error en el anuncio: {error}",
  "ui.announcement_language": "Idioma del anuncio",
  "ui.announcement_presets": "Ajustes preestablecidos de anuncios",
  "ui.announcement_sent_to_player": "Anuncio enviado a {player}",
  "ui.announcement_studio": "estudio de anuncios",
  "ui.announcement_studio_2": "Estudio de anuncios",
  "ui.announcement_target": "Objetivo del anuncio",
  "ui.announcement_to_player_preview": "Anuncio para {player}: {preview}",
  "ui.announcement_volume_boost": "Amplificación de volumen del anuncio",
  "ui.announcements": "Anuncios",
  "ui.appearance": "Apariencia",
  "ui.apply_group": "Aplicar grupo",
  
  "ui.apply_schedule": "Aplicar programación",
  "ui.artist": "Artista",
  "ui.artist_radio": "Radio de artista",
  "ui.artists": "Artistas",
  "ui.artwork": "Arte de portada",
  "ui.artwork_swipe": "Deslizar arte de portada",
  "ui.ascending": "Ascendente",
  "ui.at_least_one_player_must_stay_selected": "Al menos un reproductor debe permanecer seleccionado",
  "ui.australia": "Australia",
  "ui.auto_chooses_mobile_or_tablet_based_on_actual_width": "Selecciona automáticamente móvil o tableta según el ancho real.",
  "ui.auto_cloud_default": "Automático / Predeterminado de la nube",
  "ui.auto_extracts_colors_from_the_current_artwork_and_keeps_the_effect_subtl": "Extrae automáticamente los colores del arte actual y mantiene el efecto sutil. Fuerte hace que la paleta sea más rica y brillante.",
  "ui.auto_leaves_home_assistant_cloud_voice_defaults_untouched_manual_choices": "Automático mantiene los valores predeterminados de voz de Home Assistant Cloud sin cambios. Las opciones manuales envían un idioma explícito.",
  "ui.available": "Disponible",
  "ui.back": "Atrás",
  "ui.back_2": "Atrás",
  "ui.back_to_countries": "Volver a países",
  "ui.back_to_queue": "Volver a la cola",
  "ui.background_motion": "Movimiento de fondo",
  "ui.behavior": "Comportamiento",
  "ui.browse_covers": "Explorar portadas",
  "ui.browse_playlists_artists_albums_and_radio": "Explorar listas de reproducción, artistas, álbumes y radio",
  "ui.browser_players": "Reproductores del navegador",
  "ui.build_custom_mix": "Crear mezcla personalizada",
  "ui.building_studio_mix": "Creando mezcla de estudio...",
  "ui.button": "Botón",
  "ui.by_mood": "Por estado de ánimo",
  "ui.cache_duration_in_milliseconds_for_selected_data_requests": "Duración de la caché en milisegundos para solicitudes de datos seleccionadas.",
  "ui.cache_ttl": "TTL de caché",
  "ui.calm": "Calma",
  "ui.canada": "Canadá",
  "ui.cancel": "Cancelar",
  "ui.cancel_2": "Cancelar",
  "ui.cancel_selection": "Cancelar selección",
  "ui.card_configuration": "Configuración de la tarjeta",
  "ui.card_height": "Altura de la tarjeta",
  "ui.card_height_in_pixels": "Altura de la tarjeta en píxeles.",
  "ui.card_settings_are_managed_from_the_visual_editor": "La configuración de la tarjeta se administra desde el editor visual",
  "ui.change_song": "Cambiar canción",
  "ui.change_track": "Cambiar pista",
  "ui.chill_mix": "Mezcla relajante",
  "ui.choose_a_country_or_all_countries_to_browse_every_country_inside_the_rad": "Selecciona un país, o Todos los países para explorar cada país dentro de la pestaña de Radio.",
  "ui.choose_a_queue_position": "Selecciona una posición en la cola",
  "ui.choose_a_source_player": "Selecciona un reproductor de origen",
  "ui.choose_a_target_player": "Selecciona un reproductor de destino",
  "ui.choose_at_least_one_player": "Selecciona al menos un reproductor",
  "ui.choose_icons_text_or_both_for_the_footer": "Selecciona iconos, texto o ambos para el pie de página.",
  "ui.choose_music_assistant_players_only_the_in_card_pinning_list_shows_only": "Selecciona solo reproductores de Music Assistant. La lista de fijación dentro de la tarjeta solo muestra reproductores de Music Assistant para evitar confusiones.",
  "ui.choose_one_clear_option": "Selecciona una opción clara",
  
  "ui.choose_player": "Seleccionar reproductor",
  "ui.choose_something_from_the_quick_shelf_or_tap_the_wand_for_a_random_playl": "Selecciona algo del estante rápido o toca la varita para una lista de reproducción aleatoria.",
  "ui.choose_source": "Seleccionar origen",
  "ui.choose_target": "Seleccionar destino",
  "ui.choose_target_player": "Seleccionar reproductor de destino",
  "ui.choose_the_accent_color_for_the_mobile_layout": "Selecciona el color de acento para el diseño móvil.",
  "ui.choose_the_music": "Seleccionar la música",
  "ui.choose_the_small_buttons_shown_under_the_song_title_timer_appears_first": "Selecciona los botones pequeños que se muestran debajo del título de la canción. El temporizador aparece primero en hebreo para que se ubique en el lado derecho.",
  "ui.choose_the_source_first_playback_will_use_the_current_target": "Selecciona primero el origen. La reproducción utilizará el destino actual.",
  "ui.choose_where_to_play": "Seleccionar dónde reproducir",
  "ui.choose_whether_artwork_swipe_changes_track_or_browses_covers": "Selecciona si deslizar el arte de portada cambia de pista o explora portadas.",
  "ui.choose_whether_settings_are_controlled_from_the_in_card_ui_or_from_the_c": "Selecciona si la configuración se controla desde la interfaz de usuario de la tarjeta o desde la configuración de la tarjeta en el panel.",
  "ui.choose_which_actions_appear_in_the_main_bar": "Selecciona qué acciones aparecen en la barra principal.",
  "ui.choose_which_days_the_auto_night_mode_window_applies_to": "Selecciona a qué días se aplica la ventana del modo nocturno automático.",
  "ui.choose_which_icons_appear_in_the_quick_action_row": "Selecciona qué iconos aparecen en la fila de acciones rápidas. Limpiar todo solicita confirmación antes de desconectar los reproductores activos.",
  "ui.choose_which_players_appear_as_tiles_in_the_room": "Selecciona qué reproductores aparecen como mosaicos en la sala.",
  "ui.choose_which_players_stay_in_the_current_control_selection": "Selecciona qué reproductores permanecen en la selección de control actual.",
  "ui.choose_which_tabs_are_available_in_the_library_screen": "Selecciona qué pestañas están disponibles en la pantalla de la biblioteca.",
  "ui.choose_who_is_controlled": "Seleccionar quién es controlado",
  "ui.choosing_visual_disables_the_in_card_settings_screen": "Seleccionar Visual desactiva la pantalla de configuración dentro de la tarjeta.",
  "ui.clean_all": "Limpiar todo",
  "ui.clean_all_confirm_action": "Limpiar todo",
  "ui.clean_all_confirm_copy": "Esto desconectará todos los reproductores activos, detendrá la reproducción y vaciará sus colas. ¿Deseas continuar?",
  "ui.clean_all_confirm_title": "¿Limpiar todos los reproductores?",
  "ui.clean_the_studio_wall": "Limpiar el muro del estudio",
  "ui.clear": "Limpiar",
  "ui.clear_queue": "Vaciar cola",
  "ui.clear_search": "Limpiar búsqueda",
  "ui.clone_queue": "Clonar cola",
  "ui.close": "Cerrar",
  "ui.collapse_compact_player": "Contraer reproductor compacto",
  "ui.compact_mode": "Modo compacto",
  "ui.configure_ready_made_announcement_phrases": "Configurar frases de anuncios preestablecidas.",
  "ui.connect_this_device": "Conectar este dispositivo",
  "ui.connect_this_device_2": "Conectar este dispositivo",
  "ui.connected": "Conectado",
  "ui.connected_2": "Conectado",
  "ui.connected_players": "reproductores conectados",
  "ui.connected_players_2": "Reproductores conectados",
  "ui.connecting": "Conectando",
  "ui.connecting_2": "Conectando...",
  "ui.confirm": "Confirmar",
  "ui.connection_and_behavior": "Conexión y comportamiento",
  "ui.connects_directly_from_this_card_using_sendspin": "Se conecta directamente desde esta tarjeta usando Sendspin",
  "ui.continue": "Continuar",
  "ui.continue_2": "Continuar",
  "ui.continue_from_recent_music_assistant_activity": "Continuar desde la actividad reciente de Music Assistant.",
  "ui.continue_listening": "Continuar escuchando",
  "ui.continue_what_was_played_recently": "Continuar lo que se reprodujo recientemente",
  "ui.control_whether_the_card_background_moves_gently_and_how_strong_the_moti": "Controla si el fondo de la tarjeta se mueve suavemente y qué tan fuerte se siente el movimiento.",
  "ui.controlling": "Controlando",
  "ui.could_not_build_quick_mix_from_the_current_song": "No se pudo crear la mezcla rápida desde la canción actual",
  "ui.could_not_build_studio_mix": "No se pudo crear la mezcla de estudio",
  "ui.could_not_choose_media": "No se pudo seleccionar el medio",
  "ui.could_not_find_music": "No se pudo encontrar música",
  "ui.could_not_clone_the_queue": "No se pudo clonar la cola",
  "ui.could_not_play_label": "No se pudo reproducir: {label}",
  "ui.could_not_start_chill_mix": "No se pudo iniciar la mezcla relajante",
  "ui.could_not_start_playback": "No se pudo iniciar la reproducción",
  "ui.could_not_start_playback_2": "No se pudo iniciar la reproducción",
  "ui.could_not_start_playback_in_studio": "No se pudo iniciar la reproducción en el estudio",
  "ui.could_not_start_quick_mix": "No se pudo iniciar la mezcla rápida",
  "ui.could_not_start_radio_playback": "No se pudo iniciar la reproducción de radio",
  "ui.could_not_transfer_the_queue": "No se pudo transferir la cola",
  "ui.could_not_update_active_player_helper": "No se pudo actualizar el asistente de reproductor activo",
  "ui.create_schedule": "Crear programación",
  "ui.current_path": "Ruta actual",
  "ui.custom": "Personalizado",
  "ui.dark": "Oscuro",
  "ui.delete_scene": "Eliminar escena",
  "ui.delete_schedule": "Eliminar programación",
  "ui.descending": "Descendente",
  "ui.dictate": "Dictar",
  "ui.disabled": "Desactivado",
  "ui.disables_blur_animations_dynamic_backgrounds_and_heavy_shadows_recommend": "Desactiva el desenfoque, las animaciones, los fondos dinámicos y las sombras pesadas. Recomendado para Nest Hub y tabletas menos potentes.",
  "ui.disconnect": "Desconectar",
  "ui.disconnect_all": "Desconectar todos",
  "ui.disconnect_groups": "Desconectar grupos",
  "ui.disconnect_player_groups": "Desconectar grupos de reproductores",
  "ui.disconnect_this_device": "Desconectar este dispositivo",
  "ui.disconnected": "Desconectado",
  "ui.disconnecting": "Desconectando",
  "ui.disconnecting_player_groups": "Desconectando grupos de reproductores...",
  "ui.discover": "Descubrir",
  "ui.down": "Abajo",
  "ui.dynamic_theme": "Tema dinámico",
  "ui.edit_schedule": "Editar programación",
  "ui.enable": "Activar",
  "ui.enable_or_disable_the_footer_search_button": "Activa o desactiva el botón de búsqueda en el pie de página.",
  "ui.enable_or_disable_the_studio_button_in_the_footer_bar": "Activa o desactiva el botón del estudio en la barra del pie de página.",
  "ui.enable_the_floating_home_shortcut_button": "Activa el botón flotante de acceso directo de inicio.",
  "ui.enabled": "Activado",
  "ui.enables_switching_to_local_liked_mode": "Permite cambiar al modo de favoritos locales.",
  "ui.end_time": "Hora de finalización",
  "ui.energetic": "Energético",
  "ui.energy_and_rhythm": "Energía y ritmo",
  "ui.enter_an_announcement_first": "Ingresa un anuncio primero",
  "ui.example_quiet_jazz_greek_music_workout": "Ejemplo: jazz tranquilo, música griega, entrenamiento",

  "ui.existing_content": "Contenido existente",
  "ui.expand_player": "Expandir reproductor",
  "ui.extract_colors_from_the_current_artwork_and_apply_them_to_the_interface": "Extrae los colores del arte de portada actual y los aplica a la interfaz.",
  "ui.extreme": "Extremo",
  "ui.fallback_for_setups_that_need_an_alternate_queue_service_path": "Alternativa para configuraciones que necesitan una ruta de servicio de cola diferente.",
  "ui.fallback_mode": "Modo alternativo",
  "ui.family_friendly": "Familiar",
  "ui.favorite": "Favorito",
  "ui.favorite_action_failed": "Error en la acción de favorito",
  "ui.favorite_action_sent": "Acción de favorito enviada",
  "ui.favorite_button_entity": "Entidad del botón de favorito",
  "ui.favorite_center": "centro de favoritos",
  "ui.favorite_center_2": "Centro de favoritos",
  "ui.favorite_radio": "Radio favorita",
  "ui.favorite_updated": "Favorito actualizado",
  "ui.favorites_and_liked_music": "Favoritos y música que te gusta",
  "ui.feature_detection_player_context_and_this_device_playback_tools": "Detección de características, contexto del reproductor y herramientas de reproducción para este dispositivo.",
  "ui.find_music": "Buscar música",
  "ui.finding_music": "Buscando música",
  "ui.fixed": "Fijo",
  "ui.flow_mix": "Mezcla FLOW",
  "ui.font_scale": "Escala de fuente",
  "ui.font_size": "Tamaño de fuente",
  "ui.footer_search": "Búsqueda en el pie de página",
  "ui.footer_style": "Estilo del pie de página",
  "ui.footer_style_2": "Estilo del pie de página",
  "ui.for_example_lovelace_home_or_any_other_home_assistant_path": "Por ejemplo /lovelace/home o cualquier otra ruta de Home Assistant.",
  "ui.for_weaker_displays_turns_off_heavy_blur_animations_dynamic_theme_extrac": "Para pantallas menos potentes: desactiva el desenfoque intenso, las animaciones, la extracción del tema dinámico y el movimiento de fondo.",
  "ui.france": "Francia",
  "ui.free_style": "Estilo libre",
  "ui.free_style_quiet_jazz_greek_music_workout": "Estilo libre: jazz tranquilo, música griega, entrenamiento...",
  "ui.fresh_start": "Nuevo comienzo",
  "ui.fresh_start_2": "Nuevo comienzo",
  "ui.fri": "Vie",
  "ui.friendly_and_simple": "Amigable y simple",
  "ui.from": "De",
  "ui.general": "General",
  "ui.general_and_display": "General y Pantalla",
  "ui.germany": "Alemania",
  "ui.global_scale_for_every_interface_font_1_is_the_default_size": "Escala global para todas las fuentes de la interfaz. 1 es el tamaño predeterminado.",
  "ui.greece": "Grecia",
  "ui.grid": "Cuadrícula",
  "ui.group": "Grupo",
  "ui.group_cleared": "Grupo eliminado",
  "ui.group_cleared_2": "Grupo eliminado",
  "ui.group_speakers": "Agrupar altavoces",
  "ui.group_speakers_2": "Agrupar altavoces",
  "ui.group_updated": "Grupo actualizado",
  "ui.group_volume": "Volumen del grupo",
  "ui.group_volume_up_energetic_mix": "Grupo, subir volumen, mezcla energética",
  "ui.grouped_players": "Reproductores agrupados",
  "ui.hebrew": "Hebreo",
  "ui.history": "Historial",
  "ui.history_tabs": "Pestañas de historial",
  "ui.home": "Inicio",
  "ui.home_party_night_presets": "Ajustes preestablecidos para el hogar, fiestas o la noche",
  "ui.home_path": "Ruta de inicio",
  "ui.home_scene_prepared": "Escena de inicio preparada",
  "ui.home_shortcut": "Acceso directo de inicio",
  "ui.home_shortcut_path": "Ruta del acceso directo de inicio",
  "ui.icon_and_text": "Icono y texto",
  "ui.icon_only": "Solo icono",
  "ui.icon_plus_text": "Icono + texto",
  "ui.idle": "Inactivo",
  "ui.idle_2": "Inactivo",
  "ui.in_card_ui": "Interfaz de la tarjeta",
  "ui.includes_the_custom_theme_mode_from_the_in_card_settings_screen": "Incluye el modo de tema personalizado desde la pantalla de configuración dentro de la tarjeta.",
  "ui.info": "Información",
  "ui.israel": "Israel",
  "ui.israeli": "Israelí",
  "ui.italy": "Italia",
  "ui.items": "elementos",
  "ui.join_selected_players": "Unir reproductores seleccionados",
  "ui.kids": "Niños",
  "ui.language": "Idioma",
  "ui.larger_lyrics": "Letras más grandes",
  "ui.layout_adapted_to_height": "Diseño adaptado a la altura",
  "ui.layout_mode": "Modo de diseño",
  "ui.leave_empty_if_the_card_should_use_home_assistant_only": "Dejar vacío si la tarjeta debe usar solo Home Assistant.",
  "ui.library": "Biblioteca",
  "ui.library_2": "Biblioteca",
  "ui.library_pages": "Páginas de la biblioteca",
  "ui.library_radio": "Radio de la biblioteca",
  "ui.library_surprise": "Sorpresa de la biblioteca",
  "ui.library_tabs": "Pestañas de la biblioteca",
  "ui.library_tabs_2": "Pestañas de la biblioteca",
  "ui.light": "Claro",
  "ui.like": "Me gusta",
  "ui.like_2": "Me gusta",
  "ui.like_3": "Me gusta",
  "ui.liked": "Te gusta",
  "ui.liked_mode": "Modo de favoritos",
  "ui.liked_sync": "Sincronización de favoritos",
  "ui.list": "Lista",
  "ui.listening": "Escuchando...",
  "ui.loading": "Cargando...",
  "ui.loading_favorites": "Cargando favoritos...",
  "ui.loading_library": "Cargando biblioteca...",
  "ui.loading_lyrics": "Cargando letras...",
  "ui.loading_players": "Cargando reproductores...",
  
  "ui.loading_queue": "Cargando la cola...",
  "ui.loading_recent_items": "Cargando elementos recientes...",
  "ui.loading_schedules": "Cargando programaciones...",
  "ui.local": "Local",
  "ui.local_favorites": "Favoritos locales",
  "ui.local_favorites_2": "Favoritos locales",
  "ui.local_mode_is_only_meaningful_when_local_likes_are_enabled": "El modo local solo tiene sentido cuando los favoritos locales están activados.",
  "ui.low_light_listening": "Escucha con luz tenue",
  "ui.low_volume_and_quiet_mix": "Volumen bajo y mezcla tranquila",
  "ui.lower_volume_mood": "Ambiente de volumen bajo",
  "ui.lyrics": "Letras",
  "ui.lyrics_earlier": "Adelantar letras",
  "ui.lyrics_font_size": "Tamaño de fuente de las letras",
  "ui.lyrics_later": "Retrasar letras",
  "ui.lyrics_timing": "Sincronización de letras",
  "ui.lyrics_unavailable_right_now": "Letras no disponibles en este momento",
  "ui.ma_favorite_action_failed_with_error": "Error en la acción de favorito de Music Assistant: {error}",
  "ui.ma_interface_path": "Ruta de la interfaz de MA",
  "ui.main_bar": "Barra principal",
  "ui.main_bar_items": "Elementos de la barra principal",
  "ui.main_bar_items_2": "Elementos de la barra principal",
  "ui.main_opacity": "Opacidad principal",
  "ui.mainly_relevant_on_larger_layouts": "Relevante principalmente en diseños más grandes.",
  "ui.mass_queue_send_command_fallback": "Alternativa de mass_queue/send_command",
  "ui.matches_the_microphone_setting_from_the_in_card_settings_screen": "Coincide con la configuración del micrófono de la pantalla de configuración interna de la tarjeta.",
  "ui.media": "Medios",
  "ui.media_2": "Medios",
  "ui.media_actions": "Acciones de medios",
  "ui.media_layout": "Diseño de medios",
  "ui.media_selected_target": "Seleccionado: {media} | Destino: {target}",
  "ui.menu": "Menú",
  "ui.message": "Mensaje",
  "ui.microphone": "Micrófono",
  "ui.microphone_2": "Micrófono",
  "ui.microphone_is_disabled": "El micrófono está desactivado",
  "ui.missing_url": "Falta la URL",
  "ui.mobile": "Móvil",
  "ui.mon": "Lun",
  "ui.mood_style_or_free_text": "Estado de ánimo, estilo o texto libre",
  "ui.more_info": "Más información",
  "ui.more_info_is_unavailable_for_this_player": "La información detallada no está disponible para este reproductor",
  "ui.morning": "Mañana",
  "ui.morning_mix": "Mezcla matutina",
  "ui.move_to_next": "Mover a la posición siguiente",
  "ui.move_to_position": "Mover a la posición",
  "ui.music": "Música",
  "ui.music_assistant_config_entry_id_if_you_want_direct_integration_lookup_th": "ID de entrada de configuración de Music Assistant, si deseas la búsqueda de integración directa a través de Home Assistant.",
  "ui.music_assistant_config_entry_was_not_found": "No se encontró la entrada de configuración de Music Assistant",
  "ui.music_assistant_token": "Token de Music Assistant",
  "ui.music_assistant_url": "URL de Music Assistant",
  "ui.music_hub": "centro de música",
  "ui.music_hub_2": "Centro de música",
  "ui.mute": "Silenciar",
  "ui.mute_command_failed": "Error en el comando de silencio",
  "ui.my_studio_scene": "Mi escena de estudio",
  "ui.name_or_keyword": "Nombre o palabra clave",
  "ui.name_this_studio_scene": "Nombra esta escena de estudio...",
  "ui.netherlands": "Países Bajos",
  "ui.new_schedule": "Nueva programación",
  "ui.new_wake_schedule": "Nueva programación de despertar",
  "ui.newest": "Más reciente",
  "ui.next": "Siguiente",
  "ui.next_track_failed": "Error al pasar a la pista siguiente",
  "ui.night": "Noche",
  "ui.night_end_time": "Hora de fin de la noche",
  "ui.night_mode": "Modo nocturno",
  "ui.night_mode_auto_window": "Modo nocturno automático {start}-{end}",
  "ui.night_mode_days": "Días del modo nocturno",
  "ui.night_mode_is_always_on": "El modo nocturno está siempre activado",
  "ui.night_mode_is_off": "El modo nocturno está desactivado",
  "ui.night_mode_is_off_until_you_choose_another_mode": "El modo nocturno estará desactivado hasta que selecciones otro modo.",
  "ui.night_mode_stays_on_until_you_choose_another_mode": "El modo nocturno permanecerá activado hasta que selecciones otro modo.",
  "ui.night_schedule_updated": "Programación nocturna actualizada",
  "ui.night_start_time": "Hora de inicio de la noche",
  "ui.no_active_media": "Sin medios activos",
  "ui.no_active_players": "Sin reproductores activos",
  "ui.no_available_players": "Sin reproductores disponibles",
  "ui.no_content_found": "No se encontró contenido",
  "ui.no_dynamic_player_groups_to_disconnect": "No hay grupos dinámicos de reproductores para desconectar",
  "ui.no_extra_ma_players": "Sin reproductores de MA adicionales",
  "ui.no_extra_ma_players_2": "Sin reproductores de MA adicionales",
  "ui.no_favorites_found": "No se encontraron favoritos.",
  "ui.no_liked_media_yet": "Aún no hay medios marcados como favoritos",
  "ui.no_liked_tracks_to_play": "No hay pistas favoritas para reproducir",
  "ui.no_light_entities_found": "No se encontraron entidades de luz.",
  "ui.no_lyrics_found": "No se encontraron letras",
  "ui.no_matching_content_was_found": "No se encontró contenido coincidente",
  "ui.no_media_found": "No se encontraron medios.",
  "ui.no_media_found_for_this_search": "No se encontraron medios para esta búsqueda.",
  "ui.no_mix_content_found": "No se encontró contenido para la mezcla",
  "ui.no_music_assistant_players_were_found_check_music_assistant_and_media_pl": "No se encontraron reproductores de Music Assistant. Verifica Music Assistant y las entidades media_player.",
  "ui.no_music_assistant_players_were_found_for_pinning": "No se encontraron reproductores de Music Assistant para fijar.",
  "ui.no_next_track_in_queue": "No hay una pista siguiente en la cola",
  "ui.no_player_groups_to_disconnect": "No hay grupos de reproductores para desconectar",
  "ui.no_player_light_pairs_yet": "Aún no hay pares de reproductor-luz.",
  "ui.no_player_selected": "Ningún reproductor seleccionado",
  "ui.no_players_found": "No se encontraron reproductores",
  "ui.no_players_found_yet": "Aún no se encontraron reproductores",
  "ui.no_playlists_found": "No se encontraron listas de reproducción",

  "ui.no_queue": "Sin cola",
  "ui.no_queue_item_to_rebuild": "No hay ningún elemento de la cola para reconstruir",
  "ui.no_queue_to_clone": "No hay ninguna cola para clonar",
  "ui.no_radio_browser_countries_found": "No se encontraron países en Radio Browser",
  "ui.no_radio_stations_found": "No se encontraron estaciones de radio",
  "ui.no_recent_listening_yet": "Aún no hay reproducciones recientes.",
  "ui.no_results": "Sin resultados",
  "ui.no_results_found": "No se encontraron resultados",
  "ui.no_saved_studio_scenes_yet": "Aún no hay escenas de estudio guardadas.",
  "ui.no_scheduled_start_is_active": "No hay ningún inicio programado activo",
  "ui.no_selected_tracks_to_play": "No hay pistas seleccionadas para reproducir",
  "ui.no_sleep_timer_is_active": "No hay ningún temporizador de apagado activo",
  "ui.no_speech_was_captured": "No se capturó voz",
  "ui.no_target_players_available": "No hay reproductores de destino disponibles",
  "ui.no_target_players_available_2": "No hay reproductores de destino disponibles",
  "ui.no_tts_service_or_entity_is_configured": "No se ha configurado ninguna entidad o servicio TTS",
  "ui.no_wake_schedules_yet": "Aún no hay programaciones de despertar",
  "ui.none": "Ninguno",
  "ui.nothing_is_playing_right_now": "No se está reproduciendo nada en este momento",
  "ui.nothing_playing": "Nada en reproducción",
  "ui.now_playing": "Reproduciendo ahora",
  "ui.now_playing_2": "Reproduciendo ahora",
  "ui.off": "Apagado",
  "ui.off_2": "Apagado",
  "ui.off_disables_it_on_keeps_it_active_and_auto_follows_the_configured_time": "Apagado lo desactiva, Encendido lo mantiene activo y Automático sigue la ventana de tiempo configurada.",
  "ui.oldest": "Más antiguo",
  "ui.on": "Encendido",
  "ui.one_tap_prepares_players_grouping_volume_and_content_save_your_own_curre": "Un toque prepara los reproductores, la agrupación, el volumen y el contenido. Guarda tu destino actual del estudio como una escena local.",
  "ui.only_actions_for_the_current_target_are_shown_here": "Aquí solo se muestran las acciones para el destino actual.",
  "ui.only_music_assistant_players_are_shown_here_browser_and_local_sendspin_p": "Aquí solo se muestran los reproductores de Music Assistant. Los reproductores del navegador y locales de Sendspin están ocultos para evitar confusiones.",
  "ui.only_needed_when_using_a_direct_music_assistant_url": "Solo es necesario cuando se utiliza una URL directa de Music Assistant.",
  "ui.opacity_for_popups_and_overlays": "Opacidad para ventanas emergentes y superposiciones.",
  "ui.opacity_for_the_main_card_background": "Opacidad para el fondo de la tarjeta principal.",
  "ui.open_full_interface": "Abrir interfaz completa",
  "ui.open_full_queue": "Abrir cola completa",
  "ui.open_interface_in": "Abrir interfaz en",
  "ui.open_ma": "Abrir MA",
  "ui.open_music_assistant": "Abrir Music Assistant",
  "ui.open_music_assistant_2": "¿Abrir Music Assistant?",
  "ui.open_music_assistant_on_this_device_to_activate_the_browser_player": "Abre Music Assistant en este dispositivo para activar el reproductor del navegador",
  "ui.open_player_picker": "Abrir selector de reproductor",
  "ui.open_queue": "Abrir cola",
  "ui.open_saved_songs": "Abrir canciones guardadas",
  "ui.open_the_full_music_assistant_interface": "¿Abrir la interfaz completa de Music Assistant?",
  "ui.open_the_full_music_assistant_interface_2": "Abrir la interfaz completa de Music Assistant",
  "ui.opening_studio_library": "Abriendo la biblioteca del estudio",
  "ui.opening_timers": "Abriendo temporizadores",
  "ui.option": "Opción",
  "ui.optional": "Opcional",
  "ui.optional_2": "Opcional",
  "ui.optional_entity_used_for_an_external_favorite_button": "Entidad opcional utilizada para un botón de favorito externo.",
  "ui.optional_input_text_helper_updated_with_the_active_player_entity_id_for": "Asistente input_text opcional actualizado con el ID de entidad del reproductor activo para automatizaciones y plantillas.",
  "ui.optional_input_text_helper_updated_with_the_active_player_entity_id_for_2": "Asistente input_text opcional actualizado con el ID de entidad del reproductor activo para automatizaciones y plantillas.",
  "ui.other": "Otro",
  "ui.other_players": "Otros reproductores",
  "ui.party": "Fiesta",
  "ui.path_used_when_opening_the_music_assistant_interface": "Ruta utilizada al abrir la interfaz de Music Assistant.",
  "ui.pause": "Pausar",
  "ui.paused": "Pausado",
  "ui.per_device_in_card": "Por dispositivo / en la tarjeta",
  "ui.performance_mode": "Modo rendimiento",
  "ui.performance_mode_for_weak_devices": "Modo rendimiento para dispositivos poco potentes",
  "ui.pick_a_mood_or_type_your_own_style_studio_will_search_music_assistant_an": "Elige un estado de ánimo o escribe tu propio estilo. El estudio buscará en Music Assistant y creará una cola.",
  "ui.pinned": "Fijado",
  "ui.pinned_players": "Reproductores fijados",
  "ui.play": "Reproducir",
  "ui.play_2": "Reproducir",
  "ui.play_a_few_tracks_and_they_will_appear_here": "Reproduce algunas pistas y aparecerán aquí.",
  "ui.play_a_saved_list": "Reproducir una lista guardada",
  "ui.play_all": "Reproducir todo",
  "ui.play_an_artist": "Reproducir un artista",
  "ui.play_artwork_action": "Acción al tocar el arte de portada",
  "ui.play_everywhere": "Reproducir en todas partes",
  "ui.play_next": "Reproducir a continuación",
  "ui.play_next_and_clear_queue": "Reproducir a continuación y vaciar cola",
  "ui.play_now": "Reproducir ahora",
  "ui.play_now_and_clear_queue": "Reproducir ahora y vaciar cola",
  "ui.play_pause": "Reproducir / Pausar",
  "ui.play_queue_radio_or_remove_favorites_directly_from_studio": "Reproduce, añade a la cola, inicia radio o elimina favoritos directamente desde el estudio.",
  "ui.play_selected": "Reproducir seleccionados",
  "ui.playback_command_failed": "Error en el comando de reproducción",
  "ui.playback_command_failed_2": "Error en el comando de reproducción",
  "ui.playback_started": "Reproducción iniciada",
  "ui.player": "reproductor",
  "ui.player_2": "Reproductor",
  "ui.player_count_many": "{count} reproductores",
  "ui.player_count_one": "1 reproductor",
  "ui.player_groups_could_not_be_disconnected": "No se pudieron desconectar los grupos de reproductores",
  "ui.player_is_pinned_from_settings": "El reproductor está fijado desde la configuración",
  "ui.player_is_ready": "El reproductor está listo",
  "ui.player_is_ready_nothing_is_playing_right_now": "El reproductor está listo - no se está reproduciendo nada en este momento",
  "ui.player_on_this_device": "Reproductor en este dispositivo",
  "ui.player_selected": "Reproductor seleccionado",
  "ui.player_settings_and_dsp_presets_stay_read_only_until_music_assistant_exp": "La configuración del reproductor y los ajustes preestablecidos de DSP permanecen de solo lectura hasta que Music Assistant exponga un esquema confiable para este reproductor.",
  "ui.players": "Reproductores",
  "ui.players_queue_and_groups": "Reproductores, cola y grupos",
  "ui.playing": "Reproduciendo",
  "ui.playing_a_random_playlist": "Reproduciendo una lista de reproducción aleatoria",
  "ui.playing_a_random_radio_station": "Reproduciendo una estación de radio aleatoria",
  
  "ui.playing_on": "Playing on",
  "ui.playing_on_2": "Playing on",
  "ui.playlist": "Playlist",
  "ui.playlists": "Playlists",
  "ui.podcast": "Podcast",
  "ui.podcasts": "Podcasts",
  "ui.popup_opacity": "Popup opacity",
  "ui.preset_message": "Preset message",
  "ui.previous": "Previous",
  "ui.primary": "Primary",
  "ui.primary_target": "Primary target",
  "ui.pro_tools": "Pro tools",
  "ui.queue": "Queue",
  "ui.queue_2": "Queue",
  "ui.queue_action_failed": "Queue action failed",
  "ui.queue_action_is_not_available_for_this_player": "Queue action is not available for this player",
  "ui.queue_actions": "Queue actions",
  "ui.queue_cleared": "Queue cleared",
  "ui.queue_cleared_and_item_moved_next": "Queue cleared and item moved next",
  "ui.queue_cloned": "Queue cloned",
  "ui.queue_cockpit": "queue cockpit",
  "ui.queue_cockpit_2": "Queue Cockpit",
  "ui.queue_is_empty": "Queue is empty",
  "ui.queue_is_unavailable_for_this_player": "Queue is unavailable for this player",
  "ui.queue_item": "Queue item",
  "ui.queue_item_id_is_not_ready_yet_refresh_the_queue_and_try_again": "Queue item id is not ready yet. Refresh the queue and try again.",
  "ui.queue_results": "Queue results",
  "ui.queue_transferred": "Queue transferred",
  "ui.queues_refreshed": "Queues refreshed",
  "ui.quick_actions": "Quick actions",
  "ui.quick_actions_2": "Quick Actions",
  "ui.quick_mix": "Quick mix",
  "ui.quick_mix_started": "Quick mix started",
  "ui.quick_play": "Quick play",
  "ui.radio": "Radio",
  "ui.radio_browser": "Radio Browser",
  "ui.radio_browser_countries": "Radio Browser countries",
  "ui.radio_browser_country": "Radio Browser country",
  "ui.radio_browser_country_2": "Radio Browser country",
  "ui.radio_mode_is_not_available_for_this_media_type": "Radio mode is not available for this media type",
  "ui.radio_mode_started": "Radio mode started",
  "ui.radio_station_changed": "Radio station changed",
  "ui.radio_stations": "Radio Stations",
  "ui.random": "Random",
  "ui.random_gentle_morning_mix": "Random gentle morning mix",
  "ui.random_playlist": "Random playlist",
  "ui.random_radio": "Random radio",
  "ui.ready": "Ready",
  "ui.ready_to_play": "Ready to play",
  "ui.recent": "Recent",
  "ui.recent_continue": "Recent / Continue",
  "ui.recent_listening": "recent listening",
  "ui.recent_track": "Recent track",
  "ui.recently_added": "Recently Added",
  "ui.recently_played": "Recently Played",
  "ui.recently_played_2": "Recently played",
  "ui.recommendations_will_appear_once_homeii_flow_sees_your_queue_or_recent_l": "Recommendations will appear once HOMEii Flow sees your queue or recent listening.",
  "ui.recommended": "Recommended",
  "ui.recommended_format_hh_mm_such_as_06_00_crossing_midnight_is_supported": "Recommended format: HH:MM such as 06:00. Crossing midnight is supported.",
  "ui.recommended_format_hh_mm_such_as_22_00": "Recommended format: HH:MM such as 22:00.",
  "ui.recommended_playlist": "Recommended playlist",
  "ui.recommended_track": "Recommended track",
  "ui.reconnects_when_you_return_to_this_dashboard": "Reconnects when you return to this dashboard",
  "ui.refresh": "Refresh",
  "ui.remember_as_this_device": "Remember as this device",
  "ui.remove": "Remove",
  "ui.remove_from_selection": "Remove from selection",
  "ui.removed_from_liked": "Removed from liked",
  "ui.removed_from_music_assistant_liked": "Removed from Music Assistant liked",
  "ui.reorder_queue": "Reorder queue",
  "ui.repeat": "Repeat",
  "ui.repeat_all": "Repeat all",
  "ui.repeat_off": "Repeat off",
  "ui.repeat_one": "Repeat one",
  "ui.reset": "Reset",
  "ui.reset_lyrics_font_size": "Reset lyrics font size",
  "ui.reset_lyrics_timing": "Reset lyrics timing",
  "ui.results": "Results",
  "ui.rtl": "RTL",
  "ui.sat": "Sat",
  "ui.save_current_target": "Save current target",
  "ui.save_schedule": "Save schedule",
  "ui.scene_players_are_not_available": "Scene players are not available",
  "ui.scene_presets": "scene presets",
  "ui.scene_presets_2": "Scene Presets",
  "ui.scenes": "Scenes",
  "ui.scales_interface_icons_without_changing_button_sizes": "Scales interface icons without changing button sizes or layout.",
  "ui.scheduled_start": "Scheduled start",
  "ui.scheduled_start_activated_label": "Scheduled start activated: {label}",
  "ui.scheduled_start_cleared": "Scheduled start cleared",
  "ui.scheduled_start_failed": "Scheduled start failed",
  "ui.scheduled_start_saved": "Scheduled start saved",
  "ui.scheduled_starts_active_count": "{count} scheduled starts active",
  "ui.schedules": "Schedules",
  "ui.search": "Search",
  "ui.search_and_choose_play_next_add_radio_or_like": "Search and choose Play, Next, Add, Radio, or Like.",
  "ui.search_everything": "Search everything...",
  "ui.search_failed": "Search failed",
  "ui.search_in_queue": "Search in queue",
  "ui.search_queue_and_library": "Search queue and library...",
  "ui.search_the_library": "Search the library...",
  "ui.search_tracks_albums_artists_and_playlists": "Search tracks, albums, artists and playlists",
  "ui.searching": "Searching...",
  "ui.searching_library": "Searching library...",
  "ui.searching_smart_selection": "Searching smart selection...",
  "ui.seek": "Seek",
  "ui.select": "Select",
  "ui.select_lights": "Select light or lights",
  "ui.select_player": "Select player",
  "ui.select_2": "Select",
  "ui.select_a_player_first": "Select a player first",
  "ui.select_at_least_one_studio_player": "Select at least one Studio player",
  "ui.select_at_least_two_players_to_create_a_group": "Select at least two players to create a group",
  "ui.selected": "Selected",
  "ui.selected_music": "Selected music",
  "ui.selected_player": "Selected Player",
  "ui.selected_player_2": "Selected player",
  "ui.selected_player_3": "Selected player",
  "ui.selected_players_at_comfortable_volume": "Selected players at comfortable volume",
  "ui.selected_playlist": "Selected playlist",
  "ui.send_a_short_voice_message_or_announcement_url": "Send a short voice message or announcement URL.",
  "ui.send_a_voice_message": "Send a voice message",
  "ui.send_announcement": "Send announcement",
  "ui.sendspin_and_diagnostics": "Sendspin and diagnostics",
  "ui.set_sleep_timer": "Set sleep timer",
  "ui.set_volume": "Set volume",
  "ui.settings": "Settings",
  "ui.settings_source": "Settings source",
  "ui.show_ma_button": "Show MA button",
  "ui.show_or_hide_the_inline_next_track_row_in_now_playing": "Show or hide the inline next-track row in Now Playing.",
  "ui.show_theme_toggle": "Show theme toggle",
  "ui.show_up_next": "Show Up Next",
  "ui.show_up_next_2": "Show Up Next",
  "ui.shows_a_standalone_compact_player_tile_with_artwork_basic_controls_volum": "Shows a standalone compact player tile with artwork, basic controls, volume and an expand action.",
  "ui.shuffle": "Shuffle",
  "ui.shuffle_all": "Shuffle all",
  "ui.shuffle_favorites": "Shuffle favorites",
  "ui.shuffle_play": "Shuffle play",
  "ui.skipped_to_up_next": "Skipped to up next",
  "ui.sleep_timer": "Sleep timer",
  "ui.sleep_timer_2": "Sleep Timer",
  "ui.sleep_timer_active_remaining": "Sleep timer active: {remaining}",
  "ui.sleep_timer_added_minutes": "Added {minutes} minutes to the timer",
  "ui.sleep_timer_and_morning_playback": "Sleep timer and morning playback",
  "ui.sleep_timer_and_scheduled_playback": "Sleep timer and scheduled playback",
  "ui.sleep_timer_cleared": "Sleep timer cleared",
  "ui.sleep_timer_finished": "Sleep timer finished",
  "ui.sleep_timer_presets": "Sleep timer presets",
  "ui.sleep_timer_set_for_15_minutes": "Sleep timer set for 15 minutes",
  "ui.sleep_timer_set_minutes": "Sleep timer set for {minutes} minutes",
  "ui.sleep_timer_updated_minutes": "Sleep timer updated to {minutes} minutes",
  "ui.smaller_lyrics": "Smaller lyrics",
  "ui.smart": "Smart",
  "ui.smart_mix": "smart mix",
  "ui.smart_mix_builder": "Smart Mix Builder",
  "ui.smart_voice_selection": "Smart voice selection",
  "ui.soft_and_relaxed": "Soft and relaxed",
  "ui.soft_relaxed_music": "Soft, relaxed music",
  "ui.some_players_could_not_be_stopped_or_cleared": "Some players could not be stopped or cleared",
  "ui.songs_around_an_artist": "Songs around an artist",
  "ui.sort": "Sort",
  "ui.sort_ascending": "Sort ascending",
  "ui.sort_descending": "Sort descending",
  "ui.source_queue": "Source queue",
  "ui.spain": "Spain",
  "ui.speak_to_target_players": "Speak to target players",
  "ui.start_radio_mode": "Start radio mode",
  "ui.start_time": "Start time",
  "ui.start_time_2": "Start time",
  "ui.started_on_selected_player": "Started on selected player",
  "ui.starting_a_chill_mix": "Starting a chill mix",
  "ui.starting_quick_mix": "Starting Quick Mix...",
  "ui.stations": "stations",
  "ui.stay_active": "Stay active",
  "ui.stays_active": "Stays active",
  "ui.stop_all": "Stop all",
  "ui.stop_all_players": "Stop all players",
  "ui.stop_command_failed": "Stop command failed",
  "ui.stop_playback_clear_queues_and_disconnect_groups": "Stop playback, clear queues and disconnect groups",
  "ui.stopped_all_players_cleared_playlists_and_disconnected_groups": "Stopped all players, cleared playlists and disconnected groups",
  "ui.stops_this_browser_player": "Stops this browser player",
  "ui.strong": "Strong",
  "ui.studio": "Studio",
  "ui.studio_closed": "Studio closed",
  "ui.studio_media_action_failed": "Studio media action failed",
  "ui.studio_mix_started": "Studio mix started",
  "ui.studio_opened": "Studio opened",
  "ui.studio_pro": "studio pro",
  "ui.studio_pro_2": "Studio Pro",
  "ui.studio_scene": "Studio scene",
  "ui.studio_scene_deleted": "Studio scene deleted",
  "ui.studio_scene_saved": "Studio scene saved",
  "ui.studio_scene_was_not_found": "Studio scene was not found",
  "ui.studio_search": "studio search",
  "ui.studio_shortcut": "Studio shortcut",
  "ui.subtle": "Subtle",
  "ui.sun": "Sun",
  "ui.surprise_me": "Surprise me",
  "ui.sync": "Sync",
  "ui.sync_lyrics": "Sync lyrics",
  "ui.tablet": "Tablet",
  "ui.tap_to_start_a_sleep_timer": "Tap to start a sleep timer",
  "ui.target_players": "Target players",
  "ui.target_queue": "Target queue",
  "ui.text_announcements_use_home_assistant_tts_into_the_selected_music_assist": "Text announcements use Home Assistant TTS into the selected Music Assistant player. URL announcements use Music Assistant announcement playback.",
  "ui.text_only": "Text only",
  "ui.text_tone": "Text tone",
  "ui.theme": "Theme",
  "ui.theme_2": "Theme",
  "ui.theme_mode": "Theme mode",
  "ui.theme_toggle": "Theme toggle",
  "ui.theme_toggle_2": "Theme toggle",
  "ui.this_device": "This Device",
  "ui.this_device_2": "This device",
  "ui.this_device_player_connected": "This device player connected",
  "ui.this_device_player_disconnected": "This device player disconnected",
  "ui.thu": "Thu",
  "ui.timer": "Timer",
  "ui.timer_active_remaining": "Timer active: {remaining}",
  "ui.timers": "Timers",
  "ui.to": "To",
  "ui.today": "Today",
  "ui.track": "Track",
  "ui.track_lyrics": "Track Lyrics",
  "ui.tracks": "Tracks",
  "ui.transfer_clone_inspect_or_clear_queues_without_hiding_the_studio": "Transfer, clone, inspect, or clear queues without hiding the Studio.",
  "ui.transfer_is_unavailable_while_a_pinned_player_is_configured": "Transfer is unavailable while a pinned player is configured",
  "ui.transfer_queue": "Transfer Queue",
  "ui.transfer_queue_2": "Transfer queue",
  "ui.transfer_queue_3": "Transfer queue",
  "ui.try_again": "Try again",
  "ui.tts_entity": "TTS entity",
  "ui.tts_entity_used_by_the_announcement_screen": "TTS entity used by the announcement screen.",
  "ui.tts_language": "TTS language",
  "ui.tue": "Tue",
  "ui.turkey": "Turkey",
  "ui.turn_off": "Turn off",
  "ui.turns_off_after_run": "Turns off after run",
  "ui.turns_off_heavy_visuals_so_the_card_runs_smoother_on_nest_hub_older_tabl": "Turns off heavy visuals so the card runs smoother on Nest Hub, older tablets, and weaker displays.",
  "ui.type_a_free_style_first": "Type a free style first",
  "ui.type_an_announcement": "Type an announcement...",
  "ui.type_anything": "Type anything",
  "ui.type_what_should_be_announced": "Type what should be announced...",
  "ui.ungroup": "Ungroup",
  "ui.ungroup_2": "Ungroup",
  "ui.united_kingdom": "United Kingdom",
  "ui.united_states": "United States",
  "ui.unknown": "Unknown",
  "ui.up": "Up",
  "ui.up_next": "Up Next",
  "ui.up_next_2": "Up next",
  "ui.up_next_title": "Up next: {title}",
  "ui.upbeat_and_moving": "Upbeat and moving",
  "ui.use_any_home_assistant_path_example_lovelace_home": "Use any Home Assistant path. Example: /lovelace/home",
  "ui.use_current_view_for_home_button": "Use current view for Home button",
  "ui.use_expand_to_open_the_full_player": "Use expand to open the full player",
  "ui.uses_the_same_base_country_list_shown_in_the_in_card_settings_screen": "Uses the same base country list shown in the in-card settings screen.",
  "ui.visible_tiles": "visible tiles",
  "ui.visible_tiles_2": "Visible tiles",
  "ui.visual_editor": "Visual editor",
  "ui.assist_agent": "Assist agent",
  "ui.assist_agent_id": "Assist agent ID",
  "ui.assist_only": "Assist only",
  "ui.default_assist_agent": "Default Home Assistant Assist",
  "ui.hybrid_handles_music_locally_and_sends_unknown_commands_to_assist": "Recommended: music commands run locally on the selected player. Anything the card does not understand is sent to Home Assistant Assist.",
  "ui.hybrid_music_plus_assist": "Hybrid: Music + Assist",
  "ui.icon_size": "Icon size",
  "ui.music_only": "Music only",
  "ui.music_plus_assist": "Music + Assist",
  "ui.optional_assist_agent_id_leave_empty_for_home_assistant_default": "Optional Assist agent ID. Leave empty to use Home Assistant's default Assist agent.",
  "ui.optional_assist_agent_leave_empty_for_home_assistant_default": "Optional. Leave this on the default agent unless you have multiple Assist agents and want this card to use one specific agent.",
  "ui.show_a_push_to_talk_button_for_music_and_assist_commands": "Shows a push-to-talk button for music commands and Assist fallback.",
  "ui.speak_voice_assistant_responses_out_loud": "Speak the recognized response out loud through this browser when supported.",
  "ui.flow_assistant": "FLOW ASSISTANT",
  "ui.voice_assistant": "Voice assistant",
  "ui.voice_assistant_disabled": "Voice assistant is disabled",
  "ui.voice_assistant_listening": "Listening for a command...",
  "ui.voice_assistant_mode": "Voice assistant mode",
  "ui.voice_command_executed": "Voice command executed",
  "ui.voice_command_completed_action": "Done: {action}",
  "ui.voice_command_failed": "Voice command failed",
  "ui.voice_command_no_player": "Select a player or say the player name.",
  "ui.voice_command_not_understood": "I could not understand that command.",
  "ui.voice_command_sent": "Voice command sent",
  "ui.voice_done_status": "Done",
  "ui.voice_error_status": "Needs attention",
  "ui.voice_feedback": "Voice feedback",
  "ui.voice_group_connect_needs_players": "Say at least two player names, or select one player and say the other.",
  "ui.voice_group_connected_players": "Connected {primary} with {members}",
  "ui.voice_group_disconnect_needs_player": "Say which player group to disconnect.",
  "ui.voice_group_disconnected_player": "Disconnected the group for {player}",
  "ui.voice_input_failed": "Voice input failed",
  "ui.voice_input_is_not_supported_on_this_device": "Voice input is not supported on this device",
  "ui.voice_language_is_not_supported": "This browser does not support the selected speech recognition language.",
  "ui.voice_match_not_confident": "I found {title}, but it does not match \"{query}\" closely enough. Try saying the song and artist again.",
  "ui.voice_music_searching": "Searching music: {query}",
  "ui.voice_playing_result": "Playing {title}",
  "ui.voice_queue_transfer_needs_players": "Say the source and target player, for example: transfer queue from Living Room to Kitchen.",
  "ui.voice_queue_transferred_between": "Queue transferred from {source} to {target}",
  "ui.voice_starting_playback": "Starting {title}...",
  "ui.voice_processing_status": "Processing command...",
  "ui.voice_ready_status": "Ready",
  "ui.voice_recognition_network_failed": "Speech recognition service is unavailable. Microphone permission may be OK; check the browser, VPN, DNS, firewall, or network.",
  "ui.voice_response": "Response",
  "ui.voice_response_will_appear_here": "The response will appear here.",
  "ui.voice_search": "Voice search",
  "ui.voice_search_failed": "Voice search failed",
  "ui.voice_search_is_not_supported_on_this_device": "Voice search is not supported on this device",
  "ui.voice_transcript": "Transcript",
  "ui.voice_listening_status": "Listening...",
  "ui.waiting_for_speech": "Waiting for speech...",
  "ui.microphone_permission_or_browser_blocked": "The browser blocked speech recognition. Check microphone and browser speech settings.",
  "ui.volume": "Volume",
  "ui.volume_and_player_target": "Volume and player target",
  "ui.volume_boost": "Volume boost",
  "ui.volume_control_large_screen_only": "Volume control (large screen only)",
  "ui.volume_mode": "Volume mode",
  "ui.volume_presets": "Volume presets",
  "ui.waiting_for_this_device_player": "Waiting for this device player...",
  "ui.wake": "Wake",
  "ui.wake_schedules": "Wake schedules",
  "ui.wed": "Wed",
  "ui.week": "Week",
  "ui.what_would_you_like_to_listen_to": "What would you like to listen to?",
  "ui.will_play_next": "Will play next",
  "ui.will_play_next_in_studio": "Will play next in Studio",
  "ui.worldwide_popular": "Worldwide popular",
  "ui.add_player_light_pair": "Add pair",
  "ui.ambient_light": "Ambient light",
  "ui.ambient_light_brightness": "Light brightness",
  "ui.ambient_light_cooldown": "Light update cooldown",
  "ui.ambient_light_entities": "Default color lights",
  "ui.ambient_light_player_map": "Player -> light mapping",
  "ui.ambient_light_player_map_helper": "Use the player and color-light selectors below. Each completed row becomes a pair; clear a player or its lights to remove the pair.",
  "ui.ambient_light_transition": "Light transition",
  "ui.analog": "Analog",
  "ui.choose_only_the_lights_that_should_follow_the_music": "Choose only color-capable lights that should follow the music when no player-specific pair exists.",
  "ui.digital": "Digital",
  "ui.discover_albums": "Discover albums",
  "ui.discover_music": "Discover",
  "ui.discovery": "Discovery",
  "ui.discovery_failed": "Discovery mode failed",
  "ui.discovery_mode": "Discovery mode",
  "ui.discovery_started": "Discovery started: {mood}",
  "ui.maximum_brightness_for_music_lighting": "Maximum brightness for music lighting.",
  "ui.minimum_seconds_between_light_updates": "Minimum seconds between light updates.",
  "ui.player_light_pair_lights": "Color lights {number}",
  "ui.player_light_pair_lights_helper": "Choose color-capable lights for this Music Assistant player. Clear this field or the player to remove the pair.",
  "ui.player_light_pair_player": "Music Assistant player {number}",
  "ui.player_light_pair_player_helper": "Choose the Music Assistant player for this light pair.",
  "ui.all_genres": "All genres",
  "ui.genre": "Genre",
  "ui.mood_and_genre": "Mood and genre",
  "ui.music_by_mood_and_genre": "Music by mood and genre",
  "ui.optional_entity_for_the_power_button_leave_empty_to_stop_the_active_player": "Optional entity for the POWER button. Leave empty to stop the active player.",
  "ui.power": "Power",
  "ui.power_action_failed": "Power action failed",
  "ui.power_action_sent": "Power action sent",
  "ui.power_button": "POWER button",
  "ui.power_button_action": "POWER button action",
  "ui.power_button_entity": "POWER button entity",
  "ui.scene": "Scene",
  "ui.screensaver": "Screensaver",
  "ui.screensaver_controls": "Screensaver controls",
  "ui.screensaver_clock_mode": "Screensaver clock mode",
  "ui.screensaver_clock_size": "Screensaver clock size",
  "ui.screensaver_clock_size_helper": "Scales the tablet screensaver clock without moving the artwork.",
  "ui.screensaver_clock_x": "Clock position - LEFT / RIGHT",
  "ui.screensaver_clock_x_helper": "Lower values move left, higher values move right.",
  "ui.screensaver_clock_y": "Clock position - UP / DOWN",
  "ui.screensaver_clock_y_helper": "Lower values move up, higher values move down.",
  "ui.screensaver_message": "Screensaver message",
  "ui.screensaver_timeout": "Screensaver timeout",
  "ui.script": "Script",
  "ui.short_optional_message_shown_on_the_screensaver": "Short optional message shown on the screensaver.",
  "ui.show_previous_next_controls_on_the_screensaver": "Show previous and next buttons on the screensaver.",
  "ui.show_a_calm_clock_artwork_display_after_idle_time": "Show a calm clock and artwork display after idle time.",
  "ui.show_power_button_in_the_player_controls": "Show POWER button in the player controls.",
  "ui.show_the_fullscreen_discovery_mode_in_actions": "Show the fullscreen discovery mode in Actions.",
  "ui.smart_home": "Smart home",
  "ui.soft_transition_time_for_music_lighting": "Soft transition time for music lighting.",
  "ui.stop_player": "Stop player",
  "ui.sync_selected_lights_to_the_current_artwork_color": "Sync selected lights to the current artwork color.",
  "ui.toggle": "Toggle",
  "ui.turn_on": "Turn on",
  "ui.choose_a_category_to_browse_provider_playlists": "Choose a category to browse provider playlists before playing.",
  "ui.new_and_recommended": "New and recommended",
  "ui.provider_playlists": "Provider playlists",
});

export default messages;
